# Generated by Django 4.1.5 on 2023-03-11 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('category', models.CharField(choices=[('dairies', 'Dairies'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('fruits', 'Fruits'), ('packaged', 'Packaged Food')], default=None, max_length=20)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.company')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
