# Generated by Django 4.1.6 on 2023-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="companie",
            name="image",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
