# Generated by Django 4.1.6 on 2023-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_companie_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="companie",
            name="description",
            field=models.CharField(max_length=220, null=True),
        ),
    ]
