# Generated by Django 4.1.6 on 2023-03-20 16:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0009_companie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companie",
            name="location",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
